// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMaaVpM8iz6vlOIP8aIBcIAkTwLA9qyB8',
    appId: '1:964247675738:web:3fd88c9452f48469140963',
    messagingSenderId: '964247675738',
    projectId: 'mda-23',
    authDomain: 'mda-23.firebaseapp.com',
    storageBucket: 'mda-23.firebasestorage.app',
    measurementId: 'G-GWHYNRMHQR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkkWPNOiG_BkyvkC5xeetl_9YXH4dUL9g',
    appId: '1:964247675738:android:753ca4a0efa69411140963',
    messagingSenderId: '964247675738',
    projectId: 'mda-23',
    storageBucket: 'mda-23.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgto9y1AKpt8ezKPpCxi9J_-M-HtRX-M0',
    appId: '1:964247675738:ios:6c0b914f6ddbec25140963',
    messagingSenderId: '964247675738',
    projectId: 'mda-23',
    storageBucket: 'mda-23.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgto9y1AKpt8ezKPpCxi9J_-M-HtRX-M0',
    appId: '1:964247675738:ios:6c0b914f6ddbec25140963',
    messagingSenderId: '964247675738',
    projectId: 'mda-23',
    storageBucket: 'mda-23.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMaaVpM8iz6vlOIP8aIBcIAkTwLA9qyB8',
    appId: '1:964247675738:web:35ea2c1bac72984a140963',
    messagingSenderId: '964247675738',
    projectId: 'mda-23',
    authDomain: 'mda-23.firebaseapp.com',
    storageBucket: 'mda-23.firebasestorage.app',
    measurementId: 'G-2KRRC0GDXG',
  );
}

FirebaseAuth auth = FirebaseAuth.instance;
FirebaseFirestore store = FirebaseFirestore.instance;
